<style>
    table, th, td {
        border:1px solid black;
    }
</style>
<?php
/** @var \Luvina\Test\Block\Adminhtml\Process\ExcellentStaff $block */
$staff = $block->getStaff();
?>
<h1 style="color: #0a820b">Nhân Viên + Thưởng</h1>
<form id="form_import" method="POST"
      enctype="multipart/form-data">
    <table style="width:100%">
        <tr>
            <th>ID Nhân Viên</th>
            <th>Tên Nhân Viên</th>
            <th>Tổng Điểm</th>
            <th>Thưởng</th>
        </tr>
        <?php foreach ($staff as $item): ?>
        <?php  $result = $block->getResult($item->getData('staff_id'))?>
            <?php foreach ($result as $data): ?>
            <tr>
                <td><?= $item->getData('staff_id') ?></td>
                <td><?= $item->getData('name') ?></td>
                <td><?= $data['point'] ?></td>
                <?php if ($data['point'] >= '150'): ?>
                    <td>15.000.000</td>
                <?php elseif ($data['point'] >= '120'): ?>
                    <td>10.000.000</td>
                <?php elseif ($data['point'] >= '100'): ?>
                    <td>10.000.000</td>
                <?php else: ?>
                    <td>0</td>
                <?php endif; ?>
            </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </table>
</form>
